### ISSUE TITLE
[Bug] Error when installing v4l2loopback-dc-dkms package

### ISSUE THREAD

**Issue by Zbysiu3cytryny** [chaotic-aur/packages#3073]
### Packages:

https://aur.archlinux.org/packages/v4l2loopback-dc-dkms

### Latest chaotic version

1:2.1.2-1.1

### What happens?

==> dkms install --no-depmod v4l2loopback-dc/2.1.2 -k 6.8.1-1-cachyos-bore
Error! Bad return status for module build on kernel: 6.8.1-1-cachyos-bore (x86_64)
Consult /var/lib/dkms/v4l2loopback-dc/2.1.2/build/make.log for more information.
==> WARNING: `dkms install --no-depmod v4l2loopback-dc/2.1.2 -k 6.8.1-1-cachyos-bore' exited 10
it can't install dkms module 

### What is expected to happen?

it should install dkms module without error

### Logs

```
zbysiu@komp ~ 
❯ cat /var/lib/dkms/v4l2loopback-dc/2.1.2/build/make.log
DKMS make.log for v4l2loopback-dc-2.1.2 for kernel 6.8.1-1-cachyos-bore (x86_64)
wto, 19 mar 2024, 22:10:32 UTC
make -C /lib/modules/6.8.1-1-cachyos-bore/build M=/var/lib/dkms/v4l2loopback-dc/2.1.2/build modules
make[1]: Wejście do katalogu '/usr/lib/modules/6.8.1-1-cachyos-bore/build'
  CC [M]  /var/lib/dkms/v4l2loopback-dc/2.1.2/build/v4l2loopback-dc.o
/var/lib/dkms/v4l2loopback-dc/2.1.2/build/v4l2loopback-dc.c: In function ‘vidioc_querycap’:
/var/lib/dkms/v4l2loopback-dc/2.1.2/build/v4l2loopback-dc.c:622:3: error: implicit declaration of function ‘strlcpy’; did you mean ‘strscpy’? [-Werror=implicit-function-declaration]
  622 |   strlcpy(cap->driver, "Droidcam", sizeof(cap->driver));
      |   ^~~~~~~
      |   strscpy
cc1: some warnings being treated as errors
make[3]: *** [scripts/Makefile.build:243: /var/lib/dkms/v4l2loopback-dc/2.1.2/build/v4l2loopback-dc.o] Błąd 1
make[2]: *** [/usr/lib/modules/6.8.1-1-cachyos-bore/build/Makefile:2079: /var/lib/dkms/v4l2loopback-dc/2.1.2/build] Błąd 2
make[1]: *** [Makefile:240: __sub-make] Błąd 2
make[1]: Opuszczenie katalogu '/usr/lib/modules/6.8.1-1-cachyos-bore/build'
make: *** [Makefile:8: all] Błąd 2
zbysiu@komp ~ 
```

**Comment by Technetium1** [comment]
```
[tech@lynx chaotic-packages]$ sudo pacman -S v4l2loopback-dc-dkms
resolving dependencies...
looking for conflicting packages...

Package (2)                       New Version  Net Change  Download Size

extra/dkms                        3.0.12-1       0.11 MiB       0.04 MiB
chaotic-aur/v4l2loopback-dc-dkms  1:2.1.2-1.1    0.07 MiB       0.02 MiB

Total Download Size:   0.06 MiB
Total Installed Size:  0.18 MiB

:: Proceed with installation? [Y/n]
:: Retrieving packages...
 dkms-3.0.12-1-any                                                                                             38.4 KiB   223 KiB/s 00:00 [------------------------------------------------------------------------------------] 100%
 v4l2loopback-dc-dkms-1:2.1.2-1.1-x86_64                                                                       20.1 KiB  79.6 KiB/s 00:00 [------------------------------------------------------------------------------------] 100%
 Total (2/2)                                                                                                   58.5 KiB  89.7 KiB/s 00:01 [------------------------------------------------------------------------------------] 100%
(2/2) checking keys in keyring                                                                                                            [------------------------------------------------------------------------------------] 100%
(2/2) checking package integrity                                                                                                          [------------------------------------------------------------------------------------] 100%
(2/2) loading package files                                                                                                               [------------------------------------------------------------------------------------] 100%
(2/2) checking for file conflicts                                                                                                         [------------------------------------------------------------------------------------] 100%
(2/2) checking available disk space                                                                                                       [------------------------------------------------------------------------------------] 100%
:: Running pre-transaction hooks...
(1/1) Performing snapper pre snapshots for the following configurations...
==> root: 373
:: Processing package changes...
(1/2) installing dkms                                                                                                                     [------------------------------------------------------------------------------------] 100%
Optional dependencies for dkms
    linux-headers: build modules against the Arch kernel
    linux-lts-headers: build modules against the LTS kernel [installed]
    linux-zen-headers: build modules against the ZEN kernel
    linux-hardened-headers: build modules against the HARDENED kernel
(2/2) installing v4l2loopback-dc-dkms                                                                                                     [------------------------------------------------------------------------------------] 100%
:: Running post-transaction hooks...
(1/9) Arming ConditionNeedsUpdate...
(2/9) Install DKMS modules
==> dkms install --no-depmod v4l2loopback-dc/2.1.2 -k 6.7.5-1-cachyos-bore
==> dkms install --no-depmod v4l2loopback-dc/2.1.2 -k 6.7.10-x64v-xanmod1-1
==> dkms install --no-depmod v4l2loopback-dc/2.1.2 -k 6.6.22-1-lts
==> depmod 6.6.22-1-lts
==> depmod 6.7.10-x64v-xanmod1-1
==> depmod 6.7.5-1-cachyos-bore
(3/9) Updating initramfs...
:: Building initramfs for linux-lts (6.6.22-1-lts)
:: Building fallback initramfs for linux-lts (6.6.22-1-lts)
:: Building initramfs for linux-xanmod (6.7.10-x64v-xanmod1-1)
:: Building fallback initramfs for linux-xanmod (6.7.10-x64v-xanmod1-1)
:: Building initramfs for linux-cachyos-bore (6.7.5-1-cachyos-bore)
:: Building fallback initramfs for linux-cachyos-bore (6.7.5-1-cachyos-bore)
(4/9) Updating linux initcpios...
(5/9) Foreign/AUR package notification
=> No foreign/AUR packages found.
(6/9) Orphaned package notification...
=> No orphans found.
(7/9) Checking for .pacnew and .pacsave files...
(8/9) Performing snapper post snapshots for the following configurations...
==> root: 374
(9/9) Syncing all file systems...
```

**Comment by Technetium1** [comment]
@ptr1337 builds fine on 6.7, but not on 6.8 👀

**Comment by ptr1337** [comment]
> @ptr1337 builds fine on 6.7, but not on 6.8 👀

It is required to pull in patches for 6.8, also see:
https://gitlab.archlinux.org/archlinux/packaging/packages/v4l2loopback/-/issues/2

**Comment by ptr1337** [comment]
Its fixed now, on archlinux side.

**Comment by dr460nf1r3** [comment]
Thanks for notifying 🤗

**Comment by Zbysiu3cytryny** [comment]
no problem!
