### ISSUE TITLE
[Rebuild] floorp

### ISSUE THREAD

**Issue by thisisarnabdas** [chaotic-aur/packages#4368]
### Packages

https://aur.archlinux.org/pkgbase/floorp

### Description

Build fails since the update to 12.15.3.

Pipeline: #2650507260 (main branch, commit 14926490)

Build error:
ipc/chromium/src/base/message_pump_libevent.cc:42:1: error: use of undeclared identifier 'EVENT__SIZEOF_TIME_T'
   42 | CHECK_EVENT_SIZEOF(TIME_T, time_t);

Note: system libevent was upgraded from 2.1.12-5 to 2.1.13-1 during this same pipeline run, before the build step.

Current version deployed: 12.15.2
Attempted version: 12.15.3

**Comment by xiota** [comment]
Thanks for reporting.

A patch was dropped in the most recent release of `extra/libevent`.  I wonder if other firefox forks will be affected.

Update:
```
==> Finished making: floorp 12.15.3-1 (Tue Jul  7 16:20:14 2026)
```
